'use client'

export const dynamic = 'force-static'

import { useApp } from '@/context/AppContext'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'

const statusColors: Record<string, { bg: string; text: string }> = {
  'Paid':    { bg: 'bg-green-100', text: 'text-green-700' },
  'Unpaid':  { bg: 'bg-blue-100',  text: 'text-blue-700'  },
  'Overdue': { bg: 'bg-red-100',   text: 'text-red-700'   },
}

export default function InvoiceDetailPage() {
  const { id } = useParams()
  const router = useRouter()
  const { invoices, deleteInvoice } = useApp()

  const invoice = invoices.find(i => i.id === id)

  if (!invoice) {
    return (
      <div className="text-center py-20 text-gray-400">
        <div className="text-5xl mb-4">😕</div>
        <p className="text-base mb-4">Invoice nahi mila!</p>
        <Link href="/invoices" className="text-purple-600 font-semibold hover:underline">
          ← Invoices pe wapas jao
        </Link>
      </div>
    )
  }

  const handleDelete = () => {
    if (confirm(`"${invoice.number}" ko delete karna chahte ho?`)) {
      deleteInvoice(invoice.id)
      router.push('/invoices')
    }
  }

  const downloadPDF = async () => {
    const { jsPDF } = await import('jspdf')
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const w = pdf.internal.pageSize.getWidth()
    pdf.setFontSize(22)
    pdf.setTextColor(124, 58, 237)
    pdf.text('ClientPro Pro', 20, 25)
    pdf.setTextColor(0, 0, 0)
    pdf.setFontSize(12)
    pdf.text(`Invoice: ${invoice.number}`, 20, 40)
    pdf.text(`Status: ${invoice.status}`, 20, 50)
    pdf.text(`Client: ${invoice.client}`, 20, 60)
    pdf.text(`Project: ${invoice.project || 'Services Rendered'}`, 20, 70)
    pdf.text(`Date: ${invoice.date || new Date().toLocaleDateString()}`, 20, 80)
    pdf.line(20, 90, w - 20, 90)
    pdf.setFontSize(14)
    pdf.text('Description', 20, 100)
    pdf.text('Amount', w - 60, 100)
    pdf.setFontSize(12)
    pdf.text(invoice.project || 'Services Rendered', 20, 115)
    pdf.text(`PKR ${Number(invoice.amount).toLocaleString()}`, w - 60, 115)
    pdf.line(20, 125, w - 20, 125)
    pdf.setFontSize(14)
    pdf.setTextColor(124, 58, 237)
    pdf.text('Total:', 20, 138)
    pdf.text(`PKR ${Number(invoice.amount).toLocaleString()}`, w - 60, 138)
    pdf.setTextColor(150, 150, 150)
    pdf.setFontSize(10)
    pdf.text('Thank you for your business!', w / 2, 200, { align: 'center' })
    pdf.text('Generated by ClientPro Pro', w / 2, 207, { align: 'center' })
    pdf.save(`Invoice-${invoice.number}.pdf`)
  }

  const sc = statusColors[invoice.status] || statusColors['Unpaid']
  const today = new Date().toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' })

  return (
    <div className="max-w-2xl mx-auto">
      {/* Back + Actions */}
      <div className="flex items-center justify-between mb-8 md:ml-0 ml-12">
        <Link href="/invoices" className="text-sm text-purple-600 font-semibold hover:underline">
          ← Back to Invoices
        </Link>
        <div className="flex gap-3">
          <button
            onClick={() => window.print()}
            className="px-4 py-2 rounded-lg text-sm font-semibold text-white transition-all duration-200 hover:opacity-90"
            style={{ backgroundColor: '#7c3aed' }}
          >
            🖨️ Print
          </button>
          <button
            onClick={downloadPDF}
            className="px-4 py-2 rounded-lg text-sm font-semibold text-white transition-all duration-200 hover:opacity-90"
            style={{ backgroundColor: '#059669' }}
          >
            📄 Download PDF
          </button>
          <button
            onClick={handleDelete}
            className="px-4 py-2 rounded-lg text-sm font-semibold text-red-600 border border-red-200 hover:bg-red-50 transition-all duration-200"
          >
            🗑 Delete
          </button>
        </div>
      </div>

      {/* Invoice Card */}
      <div className="bg-white rounded-2xl shadow p-8 print:shadow-none" id="invoice-print">
        <div className="flex items-start justify-between mb-8">
          <div>
            <h1 className="text-2xl font-bold" style={{ color: '#1a1a2e' }}>
              <span style={{ color: '#7c3aed' }}>Client</span>Pro Pro
            </h1>
            <p className="text-xs text-gray-400 mt-1">Professional Invoice</p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-bold text-gray-800">{invoice.number}</div>
            <span className={`text-xs font-semibold px-3 py-1 rounded-full ${sc.bg} ${sc.text}`}>
              {invoice.status}
            </span>
          </div>
        </div>

        <div className="border-t border-gray-100 mb-6" />

        <div className="grid grid-cols-2 gap-6 mb-8">
          <div>
            <div className="text-xs text-gray-400 mb-1">Bill To</div>
            <div className="font-semibold text-gray-800">{invoice.client}</div>
            {invoice.project && <div className="text-sm text-gray-500 mt-1">📁 {invoice.project}</div>}
          </div>
          <div className="text-right">
            <div className="text-xs text-gray-400 mb-1">Invoice Date</div>
            <div className="font-semibold text-gray-800">{invoice.date || today}</div>
          </div>
        </div>

        <div className="bg-gray-50 rounded-xl overflow-hidden mb-8">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-xs text-gray-400 border-b border-gray-200">
                <th className="text-left px-4 py-3">Description</th>
                <th className="text-right px-4 py-3">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="px-4 py-4 text-gray-700">{invoice.project || 'Services Rendered'}</td>
                <td className="px-4 py-4 text-right font-semibold text-gray-800">PKR {Number(invoice.amount).toLocaleString()}</td>
              </tr>
            </tbody>
            <tfoot>
              <tr className="border-t border-gray-200">
                <td className="px-4 py-3 font-bold text-gray-800">Total</td>
                <td className="px-4 py-3 text-right font-bold text-lg" style={{ color: '#7c3aed' }}>PKR {Number(invoice.amount).toLocaleString()}</td>
              </tr>
            </tfoot>
          </table>
        </div>

        <div className="text-center text-xs text-gray-400">
          <p>Thank you for your business! 🙏</p>
          <p className="mt-1">Generated by ClientPro Pro</p>
        </div>
      </div>
    </div>
  )
}

export async function generateStaticParams() {
  return []
}
export const dynamicParams = false
